import { notFound } from 'next/navigation';
import type { Metadata } from 'next';

import { CardPreviewFrame } from '@/components/cards/card-preview';
import { env } from '@/config/env';

interface CardPageProps {
  params: {
    alias: string;
  };
}

async function fetchRenderedCard(alias: string) {
  const response = await fetch(
    `${env.apiBaseUrl}/vcards/public/${encodeURIComponent(alias)}/rendered`,
    {
      next: { revalidate: 0 },
    },
  );

  if (response.status === 404) {
    return null;
  }

  if (!response.ok) {
    throw new Error('Failed to load vCard');
  }

  return (await response.json()) as {
    vcard: {
      name: string;
      urlAlias: string;
      description?: string | null;
      templateId?: number | null;
    };
    template: {
      id: number;
      name: string;
      previewUrl?: string | null;
    } | null;
    assets: {
      html: string;
      css: string;
      js: string;
      urls: {
        preview?: string | null;
      };
    } | null;
    data: unknown;
  };
}

export async function generateMetadata({
  params,
}: CardPageProps): Promise<Metadata> {
  const { alias } = await params;
  const rendered = await fetchRenderedCard(alias);

  if (!rendered) {
    return {
      title: 'Card not found – IVGK Digital Cards',
    };
  }

  return {
    title: `${rendered.vcard.name} – Digital Card`,
    description:
      rendered.vcard.description ??
      'Digital business card generated by IVGK Digital Cards.',
    openGraph: {
      title: `${rendered.vcard.name} – Digital Card`,
      description:
        rendered.vcard.description ?? 'Explore this IVGK Digital Card.',
      images: rendered.template?.previewUrl
        ? [{ url: rendered.template.previewUrl }]
        : undefined,
    },
  };
}

export default async function CardPage({ params }: CardPageProps) {
  const { alias } = await params;
  const rendered = await fetchRenderedCard(alias);

  if (!rendered) {
    notFound();
  }

  const { vcard, template, assets, data } = rendered;

  return (
    <main className="mx-auto flex min-h-screen w-full max-w-4xl flex-col gap-6 px-4 py-10">
      <header className="text-center">
        <h1 className="text-2xl font-semibold text-slate-900">
          {vcard.name}
        </h1>
        <p className="text-sm text-slate-500">
          Powered by IVGK Digital Cards{template ? ` • ${template.name}` : ''}
        </p>
      </header>

      {assets ? (
        <CardPreviewFrame
          html={assets.html}
          css={assets.css}
          js={assets.js}
          data={data}
        />
      ) : (
        <div className="rounded-xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-600 shadow-sm">
          This card does not have an associated template yet. Reach out to the
          owner to assign one in the dashboard.
        </div>
      )}
    </main>
  );
}

